### PR TITLE
feat: Add support for edited events to run the action on every PR edit

### LINKED ISSUE #117: Allow usage of PR `edited` Event
Currently the [`edited`](https://docs.github.com/de/webhooks/webhook-events-and-payloads?actionType=edited#pull_request) Event is not supported by action.

When we don't support this event we would need to always push a commit or reopen a PR when we change the PR Title or description. So when we correct a PR after the action fails a simple change of the PR would not result in a new check against lint.

### PR DESCRIPTION
**Pull request by TheGoderGuy**
Hi, 

we found this action doing exactly what we wanted, but need support for PR edits like title changes. We tried this changed action and it worked, maybe someone else needs this too.

Closes #117

### CODE REVIEW

**Comment by TheGoderGuy** [comment]
@Namchee the workflow references to an image (version) which doesn't exist. Is there any way to get my pull request accepted or rejected? Of course, we can also fork the project, but we would like to participate instead of maintaining a side fork

**Comment by Namchee** [comment]
@TheGoderGuy, thanks for the PR!

I just noticed that it lacks `edited` event as this event is rarely fired for my personal use case 😅 

As for the workflow run, I think I messed up the workflow somewhere in one of my old PR. I will fix this ASAP.

**Comment by Namchee** [comment]
Alright, there we go! I guess I'm gonna try to edit this PR to mention #117. If `self-test` passes, I'll merge this.

**Review by Namchee — APPROVED** [review]

**Comment by Namchee** [comment]
Alright, looks good to me!

**Comment by Namchee** [comment]
@all-contributors, please add @TheGoderGuy for code.

**Comment by Namchee** [comment]
@all-contributors please add @TheGoderGuy for code

**Pull request merged**
